config/routes.rb
Rails.application.routes.draw do
  resources :tweets, only: [:new, :create, :index]
  resources :rewards, only: [:index, :show] do
    post 'redeem', on: :member
  end

  # Authentication
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'

  # Root
  root 'tweets#index'
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user, foreign_key: :author_id

  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :tweets, foreign_key: :author_id

  # validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include Rewardable

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_path unless current_user
  end
end

app/controllers/concerns/rewardable.rb
module Rewardable
  def identify_reward_sciences_user(user)
    session[:reward_sciences_user_id] = reward_sciences.users.identify(user.email)['id']
  end

  def track_reward_sciences_activity(activity_slug)
    reward_sciences.activities.track(session[:reward_sciences_user_id], activity_slug)
  end

  def list_reward_sciences_rewards
    reward_sciences.rewards.list
  end

  def show_reward_sciences_reward(reward_id)
    reward_sciences.rewards.show(reward_id)
  end

  def redeem_reward_sciences_reward(reward_id)
    reward_sciences.rewards.redeem(session[:reward_sciences_user_id], reward_id)
  rescue RewardSciences::APIException => e
    redirect_to :back, alert: e.message.split(':').last
  end

  private

  def reward_sciences
    RewardSciences::RewardSciencesClient.new(
      Rails.application.secrets.reward_sciences_access_token,
      Rails.application.secrets.reward_sciences_environment
    )
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_filter :authorize

  def index
    @rewards = list_reward_sciences_rewards['data']
  end

  def show
    @reward = show_reward_sciences_reward(params[:id])
  end

  def redeem
    redeem_reward_sciences_reward(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      identify_reward_sciences_user(user)
      redirect_to(root_path, notice: 'Signed in')
    else
      redirect_to(login_path, notice: 'Invalid email or password')
    end
  end

  def destroy
    reset_session
    redirect_to(login_path, notice: 'Signed out')
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_filter :authorize

  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = current_user.tweets.new(tweet_params)

    if @tweet.save
      track_reward_sciences_activity('tweeted')
      redirect_to(tweets_path, notice: 'Tweet successfully created.')
    else
      render :new
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      identify_reward_sciences_user(@user)
      redirect_to(root_path, notice: 'Signed up!')
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_errors.html.erb
<%# @param object %>

<% if object && object.errors.any? %>
  <p><%= object.errors.full_messages.to_sentence %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RewardSciencesRubySample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <p class="alert alert-<%= key %>"><%= value %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/rewards/index.html.erb
<h1>Rewards</h1>

<ul>
  <% @rewards.each do |reward| %>
    <li>
      <%= link_to reward_path(reward['id']) do %>
        <%= reward['title'] %>
        <%= image_tag(reward['image'], alt: reward['title']) %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/rewards/show.html.erb
<h1><%= @reward['title'] %></h1>

<%= image_tag(@reward['image'], alt: @reward['title']) %>

<%= button_to('Redeem', redeem_reward_path(@reward))%>

app/views/tweets/_form.html.erb
<%= render partial: 'errors', locals: { object: @tweet } %>

<%= form_for(@tweet) do |f| %>
  <p>
    <%= f.label :body %>
    <%= f.text_field :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/tweets/index.html.erb
<h1>Listing tweets</h1>

<% if @tweets.any? %>
  <table>
    <thead>
      <tr>
        <th>Body</th>
        <th>Author</th>
      </tr>
    </thead>

    <tbody>
      <% @tweets.each do |tweet| %>
        <tr>
          <td><%= tweet.body %></td>
          <td><%= tweet.user.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<p><%= link_to 'New Tweet', new_tweet_path %></p>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/users/new.html.erb
<h1>Signup</h1>

<%= render partial: 'errors', locals: { object: @user } %>

<%= form_for @user, url: users_path do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>